server:
  port: 8084

spring:
  application:
    name: audit-service

  data:
    mongodb:
      uri: ${SPRING_DATA_MONGODB_URI:mongodb://casino_admin:casino_secret@localhost:27017/casino_db?authSource=admin}

eureka:
  client:
    enabled: true
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka/}
    fetch-registry: true
    register-with-eureka: true
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always

logging:
  level:
    co.casino: DEBUG
